### ISSUE TITLE
Covalent reaction

### ISSUE THREAD

**Issue by xiangwenkai** [jwohlwend/boltz#108]
Thanks for your excellent work!
Covalent reactions occur with specific protein ligands, does boltz have a method to address this?
For instance, given protein 1AUR (https://www.rcsb.org/structure/1AUR), and ligand PMS: 
<img src="https://github.com/user-attachments/assets/1bdb1b7a-e6b0-43e5-a317-011747aaf6bf" alt="PMS" width="200" />  
The expected complex conformation should be:
<img src="https://github.com/user-attachments/assets/30538133-6663-4b42-bb29-639790f0485b" alt="1AUR-PMS" width="200" />
However, Boltz's prediction resulted in：
<img src="https://github.com/user-attachments/assets/a1221ca0-79c9-4d6d-88d0-885f27ff0888" alt="1AUR-PMS-boltz" width="200" />
Is there a way for me to incorporate covalent reaction details into the model to get better predictions?

**Comment by rcossio** [comment]
This is related to Issue [#65](https://github.com/jwohlwend/boltz/issues/65) (about the ring aromaticity).
The extra oxigen could be removed with something similar to issue [#94](https://github.com/jwohlwend/boltz/issues/94) in the PMS definition on the CCD library.

**Comment by benf549** [comment]
What input files/method are you using to get this output? 

If you know where the ligand attaches covalently and are using the modification syntax in the .yaml, input this could be fixed by dropping leaving atoms as mentioned in #94. If you're using the smiles or CCD to input PMS as a ligand though this might be more difficult to handle. 

It might be best to drop leaving atoms regardless of whether the ligand is being used as a modification or not but I believe right now they are not being considered at all... @gcorso any thoughts? I'm happy to make a PR which drops them unconditionally.

**Comment by xiangwenkai** [comment]
The input yaml file is:
```yaml
constraints:
- bond:
    atom1: [A, 114, OG]
    atom2: [H, 1, S]
sequences:
- protein:
    id: [A]
    sequence: MTEPLILQPAKPADACVIWLHGLGADRYDFMPVAEALQESLLTTRFVLPQAPTRPVTINGGYEMPSWYDIKAMSPARSISLEELEVSAKMVTDLIEAQKRTGIDASRIFLAGFSQGGAVVFHTAFINWQGPLGGVIALSTYAPTFGDELELSASQQRIPALCLHGQYDDVVQNAMGRSAFEHLKSRGVTVTWQEYPMGHEVLPQEIHDIGAWLAARLG
- ligand:
    ccd: PMS
    id: [H]
```
And the predict command is:
boltz predict 1AUR.yaml --use_msa_server
