### ISSUE TITLE
Bond constraints not working

### ISSUE THREAD

**Issue by bougui505** [jwohlwend/boltz#114]
We ran the boltz prediction using part of the yaml of the docstring in the yaml.py file:

```
sequences:
    - protein:
        id: A
        sequence: "MADQLTEEQIAEFKEAFSLF"
    - protein:
        id: [B, C]
        sequence: "AKLSILPWGHC"
constraints:
    - bond:
        atom1: [A, 1, CA]
        atom2: [A, 2, N]
```

The bond constraint did not change the distance between the atoms. Furthermore, the bond constraints are not listed in the file boltz_results_test2/processed/manifest.json as shown below:
```
{"records": [{"id": "test2", "structure": {"resolution": null, "method": null, "deposited": null, "released": null, "revised": null, "num_chains": 3, "num_interfaces": null}, "chains": [{"chain_id": 0, "chain_name": "A", "mol_type": 0, "cluster_id": -1, "msa_id": "test2_0", "num_residues": 20, "valid": true, "entity_id": 0}, {"chain_id": 1, "chain_name": "B", "mol_type": 0, "cluster_id": -1, "msa_id": "test2_1", "num_residues": 11, "valid": true, "entity_id": 1}, {"chain_id": 2, "chain_name": "C", "mol_type": 0, "cluster_id": -1, "msa_id": "test2_1", "num_residues": 11, "valid": true, "entity_id": 1}], "interfaces": [], "inference_options": {"binders": [], "pocket": []}}]}
```
If we measure the distance between the 2 constrained atoms in the predicted structure, we get a distance of 2.4 A instead of about 1.5 A.

We also tried to define disulfide bridge in the bond constraint section, without any success.

Thanks for your help,
Best,
