### ISSUE TITLE
NotImplementedError: Pocket constraints not implemented yet

### ISSUE THREAD

**Issue by zongmingchua** [jwohlwend/boltz#115]
I installed and verified intallation of boltz-1 in a clean conda env 
` pip install boltz -U`
`Requirement already satisfied: boltz in /home/zchua/anaconda3/envs/boltz/lib/python3.12/site-packages (0.3.2)`

Also tried clearing cache ` ~/.boltz/` as well as using a fresh install in a separate conda env but encountered the same error. Boltz-1 otherwise works fine without constraints submitted. 

yaml file that was ran:

```
version: 1  # Optional, defaults to 1
sequences:
#spike protein fragment
  - protein:
      id: 'A'
      sequence: TNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPC
#HC Fab of SW186
  - protein:
      id: 'B'
      sequence: QVQLQQSGAELVKPGASVKISCKASGVAFSSYWMNWVKQRPGKGLEWIGQIYPGDGDTNYNGKFKGKATLTADKSSSTAYMQLSSLSSEDSAVYFCARGFIATVEETMDYWGQGTSVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCAA
#LC Fab of SW186
  - protein:
      id: 'C'
      sequence: DIQMTQTTSSLSASLGDRVTISCRASQDISNYLNWYQQKPDGTVKLLIYYTSRLHSGVPSRFSGSGSGTDYSLTISNLEQEDIATYFCQQSHTLPWTFGGGTKLEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGRVLARASPSPSPSLSREAC

constraints:
  - pocket:
      binder: 'B'
      contacts: [['A', 104], ['A', 105]]

# Run command: 
# boltz predict --out_dir ~/boltz_output ~/12.18.24_8DT3_constrained.yaml --use_msa_server
```

Error message:

```
File "/home/zchua/anaconda3/envs/boltz/lib/python3.12/site-packages/boltz/data/parse/schema.py", line 796, in parse_boltz_schema
    raise NotImplementedError(msg)
NotImplementedError: Pocket constraints not implemented yet: B - [['A', 104], ['A', 105]]
```

I did previously install an older version of boltz-1 - but since a fresh install in a new conda env did not resolve this problem I am a bit stuck right now, thanks for reading :)
