### ISSUE TITLE
setting multi datasets with sample weights while trainning

### ISSUE THREAD

**Issue by derby-ding** [jwohlwend/boltz#126]
Hi guys. 
How to set multi datasets with sample weights while trainning? In official alphafold3, they use pdb-bank and distilled protein dataset, and set the sampling weights to 0.5, 0.495 ... In this work, I found target_dir in structure.ymal, but it seems not support a path list object. Need some help...

**Comment by gcorso** [comment]
Here is an example of how to use the config to set multiple datasets:

```
    - _target_: foldeverything.task.train.data.DatasetConfig
      target_dir: pdb_path
      msa_dir: msa_pdb_path
      prob: 0.5
      sampler:
        _target_: boltz.data.sample.cluster.ClusterSampler
      cropper:
        _target_: boltz.data.crop.boltz.BoltzCropper
        min_neighborhood: 0
        max_neighborhood: 40
      split: ./scripts/train/assets/validation_ids.txt
    - _target_: foldeverything.task.train.data.DatasetConfig
      target_dir: distillation_path
      msa_dir: msa_distillation_path
      prob: 0.5
      sampler:
        _target_: boltz.data.sample.cluster.ClusterSampler
      cropper:
        _target_: boltz.data.crop.boltz.BoltzCropper
        min_neighborhood: 0
        max_neighborhood: 40
```
