### ISSUE TITLE
single sequence mode

### ISSUE THREAD

**Issue by alexg-denovai** [jwohlwend/boltz#18]
Hi,

The single sequence mode I am trying to do using the "empty" keyword, with an input that looks like this:

```
>A|protein|empty
....
```

I ran 
`boltz predict --out_dir output --devices 1 optimized_example.fasta
`

and I get this error

```
    raise FileNotFoundError(msg)
FileNotFoundError: MSA file empty not found.

```

But the problem is that the program checks if the msa file called empty exists in main line 226
(https://github.com/jwohlwend/boltz/blob/703e9aba291bd47d7ee6bf4227b2772875da8068/src/boltz/main.py#L226)
For some reason I guess the msa having the property "empty" is not being turned into -1 and is therefore evaluated by this function?

I appreciate your help. Maybe add a single sequence example that works as well, as a sanity check for the users.

Thanks!

**Comment by Nicholas-Freitas** [comment]
I had the same issue after installing with pip - it was fixed for me by installing the latest github version of the software, using:
```
git clone https://github.com/jwohlwend/boltz.git
cd boltz; pip install -e .
```
as suggested in the README.

Single-sequence mode must be a new feature which is not yet in the PyPi build. Hope that helps!

**Comment by AchilleSoulieID** [comment]
I just tested with the new v0.2.0 and there is still a problem when I run a prediction without MSA (not `empty`) with a fasta file.
This `.yaml` file will work no problem: 
```yaml
version: 1  # Optional, defaults to 1
sequences:
  - protein:
      id: A
      sequence: QLEDSEVEAVAKGLEEMYANGVTEDNFKNYVKNNFAQQEISSVEEELNVNISDSCVANKIKDEFFAMISISAIVKAAQKKAWKELAVTVLRFAKANGLKTNAIIVAGQLALWAVQCG
```

But the same in `.fasta` format will throw an error : 
```
>A|protein
QLEDSEVEAVAKGLEEMYANGVTEDNFKNYVKNNFAQQEISSVEEELNVNISDSCVANKIKDEFFAMISISAIVKAAQKKAWKELAVTVLRFAKANGLKTNAIIVAGQLALWAVQCG
```

It will work if I set the msa to `empty`.
