### ISSUE TITLE
Issue with output-format pdb vs output-format mmcif

### ISSUE THREAD

**Issue by ameya98** [jwohlwend/boltz#209]
Hi, thanks for the wonderful implementation and repo!

I was experimenting with Boltz1 on a kinase:
```
version: 1  # Optional, defaults to 1
sequences:
  - protein:
      id: ABL
      sequence: GAMDPSSPNYDKWEMERTDITMKHKLGGGQYGEVYEGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMTYGNLLDYLRECNRQEVNAVVLLYMATQISSAMEYLEKKNFIHRDLAARNCLVGENHLVKVADFGLSRLMTGDTYTAHAGAKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYELLEKDYRMERPEGCPEKVYELMRACWQWNPSDRPSFAEIHQAFETMFQES
```
With `--output_format mmcif`, I get something very reasonable as visualized in PyMOL:

![Image](https://github.com/user-attachments/assets/5643dccc-ca3e-4f9f-a0aa-c13fa8212cc8)

but with `--output_format pdb`:

![Image](https://github.com/user-attachments/assets/cf1d1f15-0b45-4807-bead-bac18fceeb3b)

Am I doing something wrong?
