### ISSUE TITLE
retraining the confidence module

### ISSUE THREAD

**Issue by dugu9sword** [jwohlwend/boltz#216]
Hi,

Thank you for your great work! 

I tried to re-train Boltz on my machine, but encountered some issues. After training the structure prediction module, I attempted to train the confidence module. But some errors occur when computing the `PAE` loss.

The error message is:

```
[rank1]:   File "/opt/tiger/boltz/src/boltz/model/loss/confidence.py", line 581, in compute_frame_pred
[rank1]:     frames_idx_pred[i, :, token_idx : token_idx + num_atoms, :] = frames
[rank1]: RuntimeError: The expanded size of the tensor (69) must match the existing size (408) at non-singleton dimension 1.  Target sizes: [1, 69, 3].  Tensor sizes: [408, 3]
```

My code is based on version 0.4.1.

The `model` part of the config file is:
```yaml
model:
  structure_prediction_training: false
  confidence_prediction: true
  alpha_pae: 1
  confidence_imitate_trunk: true
  confidence_model_args:
    num_dist_bins: 64
    max_dist: 22
    add_s_to_z_prod: true
    add_s_input_to_s: true
    use_s_diffusion: true
    add_z_input_to_z: true
```
