### ISSUE TITLE
saved plDDT in CIF for ligand is only the first ligand atom's pLDDT

### ISSUE THREAD

**Issue by tubiana** [jwohlwend/boltz#238]
Hi!

I wanted to repport that the pLDDT reported for ligands in the bfactor columns in the CIF files are only the first atom's pLDDT repported in the npz matrix. 

Here's the cif file text for the ligand with the pLDDT always at 64.540
![Image](https://github.com/user-attachments/assets/10a6c0c7-5a34-444c-b1ad-53374c714ab6)

Here's the corresponding values from the ligands from the NPZ file : 

![Image](https://github.com/user-attachments/assets/a926480f-157b-40b7-911b-46c958e946c3)

Best,
T.

**Comment by benf549** [comment]
Thanks for pointing this out @tubiana, I've also noticed some weirdness working with the pLDDTs written to the bfactor columns of Boltz generated PDB and CIF files. 

I think this points to a larger bug with how the pLDDT values indexed when writing PDB files and mmCIF files. I set up a simple test case and think I have a fix:

![Image](https://github.com/user-attachments/assets/d8d3ee61-2161-449a-bd51-b92fc0cea937)

As shown in the screenshot above, if you predict a structure with two ligands, the second ligand's pLDDT value written to its bfactor column is actually the pLDDT of the second atom of the first ligand. You can replicate this with the following input.yaml file with `--seed 1` and comparing the bfactors to those written to the `.npz` file.

```yaml
version: 1  # Optional, defaults to 1
sequences:
  - protein:
      id: [A]
      sequence: AAAAAAAAA
      msa: empty
  - ligand:
      id: [B]
      smiles: 'C1=CC=CC=C1'
  - ligand:
      id: [C]
      smiles: 'C1=CC=C(C=C1)C(=N)N'
```

I've updated the pdb and mmcif writing code to offset the indices of the plddt tensor used to select the bfactors to account for the lengths of the ligand. This can get a bit tricky if ligands are placed in between polymers vs at the beginning vs at the end. My patch does seem to resolve this contrived test case well though more testing might be needed to make sure all edge cases are handled:

```yaml
version: 1  # Optional, defaults to 1
sequences:
  - protein:
      id: [A]
      sequence: MVTPEGNVSLVDESLLVGVTDEDRAVRSAHQFYERLIGLWAPAVMEAAHELGVFAALAEAPADSGELARRLDCDARAMRVLLDALYAYDVIDRIHDTNGFRYLLSAEARECLLPGTLFSLVGKFMHDINVAWPAWRNLAEVVRHGARDTSGAESPNGIAQEDYESLVGGINFWAPPIVTTLSRKLRASGRSGDATASVLDVGCGTGLYSQLLLREFPRWTATGLDVERIATLANAQALRLGVEERFATRAGDFWRGGWGTGYDLVLFANIFHLQTPASAVRLMRHAAACLAPDGLVAVVDQIVDADREPKTPQDRFALLFAASMTNTGGGDAYTFQEYEEWFTAAGLQRIETLDTPMHRILLARRATEPSAVPEGQASENLYFQ
      msa: empty
  - ligand:
      id: [B, C]
      smiles: 'N[C@@H](Cc1ccc(O)cc1)C(=O)O'
  - dna:
      id: [D]
      sequence: GATACACA
  - ligand:
      id: [E]
      ccd: ZN
  - ligand:
      id: [F]
      smiles: 'C1=CC=C(C=C1)C(=N)N'
```
