### ISSUE TITLE
id error in yaml

### ISSUE THREAD

**Issue by amoschoomy** [jwohlwend/boltz#241]
Failed to process control_testing_batch_1_input/ir_2023-07-17_0413_64b4bff901f8c_extracted.tsv_cdr3/175507.yaml. Skipping. Error: '17550'.

This is my yaml file:
```
sequences:
- protein:
    id: '175507'
    msa: /scratch/project/tcr_ml/boltz1/control_testing_batch_1/control_testing_batch_1_msa/ir_2023-05-22_0558_646b0473c0d84_extracted.tsv_cdr3/ir_2023-05-22_0558_646b0473c0d84_extracted.tsv_cdr3_175507.a3m
    sequence: CVSSDTNAGELFF
```

Why is id of more than 5 characters length throws an error? My sample of amino acids has 300000 sequences to be predicted and it throws an error for any sequences which have an id more than 5 digits?

I know a workaround is to trim to encode the id in less than 5 characters long, but I would like to know why is this a limitation
