### ISSUE TITLE
Boltz-2 affinity prediction fails when using a CCD ligand

### ISSUE THREAD

**Issue by tomgoddard** [jwohlwend/boltz#302]
The affinity.yaml example runs without errors with my Boltz 2.0.2 installation (Github SHA faa24790861edfc87dd52555d2bd8ad39a39aa85) and produces correct output but if I replace the SMILES string ligand with a CCD ligand EQT in affinity.yaml the structure prediction including the ligand works but the affinity prediction fails with hundreds of warnings

    Cropper failed on affinity with error zero-size array to reduction operation minimum which has no identity. Skipping.

followed by hundreds of tracebacks ending with

    RecursionError: maximum recursion depth exceeded

The full input and output is in the attached zip file.  The output is in file named "output". 

[affinity_test2.zip](https://github.com/user-attachments/files/20635987/affinity_test2.zip)

Boltz 2.0.2 was run using

    boltz predict affinity.yaml --use_msa_server >& output

Here is the modified affinity.yaml file:

```
version: 1  # Optional, defaults to 1
sequences:
  - protein:
      id: A
      sequence: MVTPEGNVSLVDESLLVGVTDEDRAVRSAHQFYERLIGLWAPAVMEAAHELGVFAALAEAPADSGELARRLDCDARAMRVLLDALYAYDVIDRIHDTNGFRYLLSAEARECLLPGTLFSLVGKFMHDINVAWPAWRNLAEVVRHGARDTSGAESPNGIAQEDYESLVGGINFWAPPIVTTLSRKLRASGRSGDATASVLDVGCGTGLYSQLLLREFPRWTATGLDVERIATLANAQALRLGVEERFATRAGDFWRGGWGTGYDLVLFANIFHLQTPASAVRLMRHAAACLAPDGLVAVVDQIVDADREPKTPQDRFALLFAASMTNTGGGDAYTFQEYEEWFTAAGLQRIETLDTPMHRILLARRATEPSAVPEGQASENLYFQ
  - ligand:
      id: B
      ccd: EQT
properties:
  - affinity:
      binder: B
```
