### ISSUE TITLE
Are pocket restraints with affinity prediction working?

### ISSUE THREAD

**Issue by KirillShmilovich** [jwohlwend/boltz#306]
I've tried a number of examples defining lists of residue indexes for the purposes of defining pocket constraints:

e.g., in the `contacts` field.
```
constraints:
  - pocket:
      binder: B
      contacts: [[A,1]]
      max_distance: 8
```  

Even when defining example residue indexes (like 1 or the last possible index) appears not to impact the ligand placement. 

Starting from a template ligand-bound structure, I'm concerned that the tools i'm using are not able to accurately return the correctly expected residue indexing for this field. I'm wondering if there is any guidance on how given a template structure I can get a list of residue indexes from the ligand contacts I could use for this purpose.

Thanks in advance and happy to clarify thing further!
