### ISSUE TITLE
2.1.0 TypeError: Attention.forward() got an unexpected keyword argument 'biases'

### ISSUE THREAD

**Issue by mjacksonhill** [jwohlwend/boltz#346]
```
boltz predict ./TeGST.yaml \
--out_dir ./yaml --use_msa_server \
--diffusion_samples 5 --recycling_steps 10 \
--use_potentials --affinity_mw_correction \
--cache ./cache --override
```
YAML:
```
version: 1
sequences:
  - protein:
      id: [A, B]
      sequence: [sequence omitted]
      msa: ./msa.csv
  - ligand:
      id: C
      ccd: GSH
  - ligand:
      id: D
      smiles: [smiles omitted]
properties:
    - affinity:
        binder: C
        binder: D
```

Also tried with affinity prediction for only ligand D, same issue. Using v2.1.0, h200 GPU. Hopefully the attached log file is informative-- looks like this may have something to do with the 2.1.0 update?

[slurm-495167.log](https://github.com/user-attachments/files/20688226/slurm-495167.log)

**Comment by zhenjiagan** [comment]
Hi,

I used 2.1.1 and ran the following YAML file with the same error
`TypeError: Attention.forward() got an unexpected keyword argument 'biases'`
YAML:
```
version: 1  # Optional, defaults to 1
sequences:
  - protein:
      id: A
      sequence: MVTPEGNVSLVDESLLVGVTDEDRAVRSAHQFYERLIGLWAPAVMEAAHELGVFAALAEAPADSGELARRLDCDARAMRVLLDALYAYDVIDRIHDTNGFRYLLSAEARECLLPGTLFSLVGKFMHDINVAWPAWRNLAEVVRHGARDTSGAESPNGIAQEDYESLVGGINFWAPPIVTTLSRKLRASGRSGDATASVLDVGCGTGLYSQLLLREFPRWTATGLDVERIATLANAQALRLGVEERFATRAGDFWRGGWGTGYDLVLFANIFHLQTPASAVRLMRHAAACLAPDGLVAVVDQIVDADREPKTPQDRFALLFAASMTNTGGGDAYTFQEYEEWFTAAGLQRIETLDTPMHRILLARRATEPSAVPEGQASENLYFQ
      msa: ./examples/msa/seq1.a3m
  - ligand:
      id: B
      ccd: SAH
  - ligand:
      id: C
      smiles: 'N[C@@H](Cc1ccc(O)cc1)C(=O)O'
properties:
  - affinity:
      binder: C
```
Or is there something wrong with the way YAML is written?
