### ISSUE TITLE
Depth of auto-generated MSAs

### ISSUE THREAD

**Issue by max-overath** [jwohlwend/boltz#39]
The MSAs that got generated for my predictions only contain a couple of sequences. 
Is this due to limitations of the MMSeq2 sever or can this be adjusted?

**Comment by jwohlwend** [comment]
Yeah that d be due to the server. Maybe try this (https://zhanggroup.org/DeepMSA/) and see if you're getting a much deeper MSA? Maybe your sequence just doesn't have many homologues?

**Comment by Overathed** [comment]
Thanks for the answer! Yes when using the DeepMSA I get a much deeper MSA. However, it is also deeper when using colabfold which should also use a MMSeq2 server if I'm not mistaken?

**Comment by jwohlwend** [comment]
Would you mind sharing your input config? I can take a look

**Comment by heol1** [comment]
Is the query sequence a hetero-multimeric protein? If so, I had the same issue. 
In ColabFold, it queries MMseqs2 API twice: one for each chain and the other for the "pair" mode. 
https://github.com/sokrypton/ColabFold/blob/e2ca9e8f992cd65c986de5b64885d5572d8b8ad9/colabfold/batch.py#L817-L857
In contrast, the current implementation of Boltz, `compute_msa`, calls the API only once for the "pair" mode. 
https://github.com/jwohlwend/boltz/blob/e43f9101886ea6c290d6b1e0ada3796f0e798d88/src/boltz/main.py#L178
This might the reason why you have a shallow MSA...

**Comment by jadolfbr** [comment]
So should it do the multiples then? Does that match the benchmarking?

**Comment by jwohlwend** [comment]
Looking into it, will report back

**Comment by max-overath** [comment]
@heol1 yes exactly it's a hetero multimer. When I run the chains individually I get much deeper MSAs

**Comment by max-overath** [comment]
@jwohlwend input fasta for reference: 

```
>A|protein
QVQLQESGGGLVQAGGSLRLSCAGSGDALGSYTMGWFRQAPGGGRDLVAQISVDGSSTYHLDSVRGRFTASRDNAKNTVYLEMNSLNSEDTAVYYCAAAPLLRGNYDYWGQGTQVTVSS
>B|protein
IRCFITPDITSKDCPNGHVCYTKTWCDAFCSIRGKRVDLGCAATCPTVKTGVDIQCCSTDNCNPFPTRKRP
```

**Comment by amelie-iska** [comment]
I'm having similar issues. I tried this:
```
version: 1  # Optional, defaults to 1
sequences:
  - protein:
      id: A
      sequence: MGDWSALGRLLDKVQAYSTAGGKVWLSVLFIFRILLLGTAVESAWGDEQSAFVCNTQQPGCENVCYDKSFPISHVRFWVLQIIFVSTPTLLYLAHVFYLMRKEEKLNRKEEELKMVQNEGGNVDMHLKQIEIKKFKYGLEEHGKVKMRGGLLRTYIISILFKSVFEVGFIIIQWYMYGFSLSAIYTCKRDPCPHQVDCFLSRPTEKTIFIWFMLIVSIVSLALNIIELFYVTYKSIKDGIKGKKDPFSATNDAVISGKECGSPKYAYFNGCSSPTAPMSPPGYKLVTGERNPSSCRNYNKQASEQNWANYSAEQNRMGQAGSTISNTHAQPFDFSDEHQNTKKMAPGHEMQPLTILDQRPSSRASSHASSRPRPDDLEI
  - protein:
      id: B
      sequence: MGTFEEVP
```
with the command:
```
boltz predict examples/multimer.yaml --recycling_steps 20  --diffusion_samples 10 --use_msa_server
```
and both MSAs for the individual, as well as the pair, are single sequences only. Using ColabFold, I get much deeper MSAs (and much better predictions).
