### ISSUE TITLE
Ran out of memory error

### ISSUE THREAD

**Issue by florionpeni** [jwohlwend/boltz#402]
I'm trying to run affinity prediction for a protein–ligand complex using `boltz predict`, but the structure prediction step fails silently with a memory warning. The affinity prediction then crashes because the `.npz` file is missing.

```
WARNING: ran out of memory, skipping batch
...
FileNotFoundError: [Errno 2] No such file or directory: 'boltz_results_input_mofezolac/predictions/input_mofezolac/pre_affinity_input_mofezolac.npz'
```
What is the recommended way to reduce memory usage during structure prediction? I saw mentions in other issues and PRs (e.g. #235, #264) of chunking or `bfloat16` support, how can I activate those?

**Command used**

```bash
boltz predict input_mofezolac.yaml \
  --accelerator gpu \
  --devices 1 \
  --sampling_steps 200 \
  --diffusion_samples 5 \
  --affinity_mw_correction \
  --use_msa_server
```

**System**

GPU: RTX 2080 Ti (11 GB)
CUDA: 12.2
Torch: 2.5.1+cu121
Lightning: 2.5.0
Boltz: 2.0.3
Python: 3.12
Running on: Local Linux + Anaconda

**YAML snippet:**

```yaml
sequences:
  - protein:
      id: A
      sequence: [very long COX-1 sequence ~600aa]
  - ligand:
      id: L
      smiles: "COc1ccc(-c2noc(CC(=O)O)c2-c2ccc(OC)cc2)cc1"
templates:
  - cif: 6y3c_updated.cif
    chain_id: A
    template_id: A
constraints:
  - pocket:
      binder: L
      contacts:
        - [A, 116]
        - [A, 120]
        # ...
```
Would appreciate any advice on which command-line arguments I can use to reduce memory (especially for consumer GPUs). I am also trying to run this on an HPC platform and will update on output.
