### ISSUE TITLE
Pocket contact constraint is not respected

### ISSUE THREAD

**Issue by davidslochower** [jwohlwend/boltz#418]
I'm having trouble with pocket constraints in `boltz` 2.0.3. In particular, I'm seeing protein-ligand poses where the ligand is not within `max_distance` of the `contacts` defined in the YAML. This could be related to https://github.com/jwohlwend/boltz/issues/306 but I see this a) even without affinity prediction, and b) without defining a template.

For a simple example like this:
```
sequences:
    - protein:
        id: [A]
        sequence: PGWR...
    - ligand:
        id: [B]
        smiles: 'Cc1c(C2C...'
constraints:
    - pocket:
        binder: B
        contacts: [[A, 206]]
        max_distance: 10
```

Run using `boltz predict template.yaml --use_msa_server` I'm getting a pose that is ~35 Angstroms from the contact (residue 206).

I'm not entirely sure how to interpret the JSON, but the `confidence_score` is ~0.81. Are there other parameters I should try?
