### ISSUE TITLE
Cyclic peptides

### ISSUE THREAD

**Issue by Mhealy9999** [jwohlwend/boltz#425]
I'm trying to predict a cyclic peptide against a protein complex using the .yaml below. However, when I checked the structure file I had a linear peptide. I tried the example with and without msa and again only saw a linear peptide. Image is of the example peptide:

<img width="840" alt="Image" src="https://github.com/user-attachments/assets/29233bb8-afc7-4881-b65a-691cf91865d8" />

```
version: 1  # Optional, defaults to 1
sequences:
  - protein:
      id: A
      sequence: GLPEGEVDLLRYDPLP
      cyclic: true
      msa: empty
  - protein:
      id: B
      sequence: PVDTYNNILTVLKLKHFHPLFEYFDYESRKSMSCYVLSNVLDYNTEIVSQDQVDSIMNLVSTLIQDQPDQPVEDPDPEDFADEQSLVGRFIHLLRSEDPDQQYLILNTARKHFGAGGNQRIRFTLPPLVFAAYQLAFRYKENSKVDDKWEKKCQKIFSFAHQTISALIKAELAELPLRLFLQGALAAGEIGFENHETVAYEFMSQAFSLYEDEISDSKAQLAAITLIIGTFERMKCFSEENHEPLRTQCALAASKLLKKPDQGRAVSTCAHLFWSGRNTDKNGEELHGGKRVMECLKKALKIANQCMDPSLQVQLFIEILNRYIYFYEKENDAVTIQVLNQLIQKIREDLPNLESSEETEQINKHFHNTLEHLRLRRESPESEGPIYEGLIL
      msa: /scratch/project/macrocyclic_lib/RFpeptide/RFdiffusion/outputs/test/msa/35_cde3d.a3m
  - protein:
      id: C
      sequence: MAGHRLVLVLGDLHIPHRCNSLPAKFKKLLVPGKIQHILCTGNLCTKESYDYLKTLAGDVHIVRGDFDENLNYPEQKVVTVGQFKIGLIHGHQVIPWGDMASLALLQRQFDVDILISGHTHKFEAFEHENKFYINPGSATGAYNALETNIIPSFVLMDIQASTVVTYVYQLIGDDVKVERIEYKKP
      msa: /scratch/project/macrocyclic_lib/RFpeptide/RFdiffusion/outputs/test/msa/29_163cc.a3m
```
