### ISSUE TITLE
Presence of Covalent Bonds Between Protein and Ligand in Results

### ISSUE THREAD

**Issue by SejeongPark8354** [jwohlwend/boltz#54]
First, thank you for your excellent research.
Based on your research, I attempted to predict protein-ligand structures (a kind of binding mode analysis) using single protein:single ligand combinations as shown in the input yaml below.
However, when I checked the resulting cif file as shown in the image, it appears that there are bonds connecting the protein and ligand. Is this a normal outcome? Could this be a visualization artifact?

input yaml:
```
version: 1  # Optional, defaults to 1
sequences:
  - protein:
      id: [A]
      sequence: GMPGVIPSESNGLSRGSPSKKNRLSLKFFQKKETKRALDFTDSQENEEKASEYRASEIDQVVPAAQSSPINCEKRENLLPFVGLNNLGNTSYLNSILQVLYFCPGFKSGVKHLFNIISRKKEALKDEANQKDKGNCKEDSLASYELICSLQSLIISVEQLQASFLLNPEKYTDELATQPRRLLNTLRELNPMYEGYLQHDAQEVLQCILGNIQETCQLLKKEEVKNVAELPTKVEEIPHPKEEMNGINSIEMDSMRHSEDFKEKLPKGNGKRKSDTEFGNMKKKVKLSKEHQSLEENQRQTRSKRKATSDTLESPPKIIPKYISENESPRPSQKKSRVKINWLKSATKQPSILSKFCSLGKITTNQGVKGQSKENECDPEEDLGKCESDNTTNGCGLESPGNTVTPVNVNEVKPINKGEEQIGFELVEKLFQGQLVLRTRCLECESLTERREDFQDISVPVQEDELSKVEESSEISPEPKTEMKTLRWAISQFASVERIVGEDKYFCENCHHYTEAERSLLFDKMPEVITIHLKCFAASGLEFDCYGGGLSKINTPLLTPLKLSLEEWSTKPTNDSYGLFAVVMHSGITISSGHYTASVKVTDLNSLELDKGNFVVDQMCEIGKPEPLNEEEARGVVENYNDEEVSIRVGGNTQPSKVLNKKNVEAIGLLAAQKSKADYELYNKASNPDKVASTAFAENRNSETSDTTGTHESDRNKESSDQTGINISGFENKISYVVQSLKEYEGKWLLFDDSEVKVTEEKDFLNSLSPSTSPTSTPYLLFYKKL
  - ligand:
      id: [B]
      smiles: FC(F)(C1=CN(C(C)C)C(C2=CC=C(CN3N=CC4=C3N=C(C5=C(C6CC6)N=CN=C5OC)N=C4)C=C2)=N1)F
```

![image](https://github.com/user-attachments/assets/64135842-bc18-4940-b3b4-e79317250ad7)
