### ISSUE TITLE
Bug found!

### ISSUE THREAD

**Issue by yx0516** [jwohlwend/boltz#80]
When i use the following yaml file, i get the complex structure sucessfully.

sequences:
- protein:
    id: A
    sequence: MNACPHSDTLTIDPMITDLAGETSRLRAAGPLTRIDLLGVPALAVTGHTLARQLLTDTRLVKDINAWSLWQSGTVTRQWPLIGMIDVDRSMFTVDGPEHRRLRIKTTQALTRRRLDALKPTIERYVAELLDDLERAGADGAVVDLKSVFAYPLPMRVISALMGVPSEDQEQLLTWYKAFFSILTPQDERLRVIDEMHGYFTEMVRRKTAEPGDDLTSALIYATDGETPLTEEEVIGNLQALVAAGHETTVSLILTAVRALLSHPEQLRLVRDGEIGWETAIEETLRWDGPVIHLLMRFATEDIDLGDAVIPRGEGVVMSYRAIGRDITVHGADADDFDITRATAARHISFGHGPHICPGAALARLEAAIALPALFTRFPHLHPALPLDQIPNLPVLTQNDLSHFPIHLGR
- dna:
    id: B
    sequence: GGGAATGGCAGTATTCATCCACAATG
- dna:
    id: C
    sequence: CCATTGTGGATGAATACTGCCATTCC
- rna:
    id: D
    sequence: GGGUCUCGCGGAACCGGUGAGUACACCGGAAUCCAGGAAACUGGAUUUGGGCGUGCCCCCGCGAGACC
version: 1

However, when i use only the protein sequence in the yaml file, i got no results with "| WARNING: ran out of memory, skipping batch" 
under the same free GPU card with no other runing process. The yaml file as following:

sequences:
- protein:
    id: A
    sequence: MNACPHSDTLTIDPMITDLAGETSRLRAAGPLTRIDLLGVPALAVTGHTLARQLLTDTRLVKDINAWSLWQSGTVTRQWPLIGMIDVDRSMFTVDGPEHRRLRIKTTQALTRRRLDALKPTIERYVAELLDDLERAGADGAVVDLKSVFAYPLPMRVISALMGVPSEDQEQLLTWYKAFFSILTPQDERLRVIDEMHGYFTEMVRRKTAEPGDDLTSALIYATDGETPLTEEEVIGNLQALVAAGHETTVSLILTAVRALLSHPEQLRLVRDGEIGWETAIEETLRWDGPVIHLLMRFATEDIDLGDAVIPRGEGVVMSYRAIGRDITVHGADADDFDITRATAARHISFGHGPHICPGAALARLEAAIALPALFTRFPHLHPALPLDQIPNLPVLTQNDLSHFPIHLGR
version: 1

**Comment by xinyu-dev** [comment]
Same issue here.

My instance: 1xA10 (24GB)
Input: 

```yaml
version: 1
sequences:
  - protein:
      id: A
      sequence: DIQMTQSPSSLSASVGDRVTITCRASQGIRNYLAWYQQKPGKAPKLLIYAASTLQSGVPSRFSGSGSGTDFTLTISSLQPEDVATYYCQRYNRAPYTFGQGTKVEIK
  - protein:
      id: B
      sequence: EVQLVESGGGLVQPGRSLRLSCAASGFTFDDYAMHWVRQAPGKGLEWVSAITWNSGHIDYADSVEGRFTISRDNAKNSLYLQMNSLRAEDTAVYYCAKVSYLSTASSLDYWGQGTLVTVSS
```
Memory usage is low but it still outputs `| WARNING: ran out of memory, skipping batch` error and the prediction fails
