### ISSUE TITLE
Bond constraints and KeyError

### ISSUE THREAD

**Issue by darthmodel** [jwohlwend/boltz#92]
Hi, 

Can someone help me understand how to set up bond constraint? I can't seem to get boltz to correctly parse the yaml file. Here is the constrain section. 

```
constraints:
  - bond:
      atom1: [A, 77, NZ]
      atom2: [C, 1, O72]
  - bond:
      atom1: [A, 8, NZ]
      atom2: [C, 1, O12]
```

It always ends up with a KeyError on `atom1` of the first bond. Is it because constraints are only available through the github repo. I installed mine via `pip install boltz`. 

Thanks,
G

**Comment by gcorso** [comment]
Hi @darthmodel could you share a full input file for us to reproduce the error?

**Comment by darthmodel** [comment]
Hi @gcorso thanks for getting back and also for making the model available. Here is the input file. 

```
version: 1
sequences:
  - protein:
      id: [A]
      sequence: "SSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENLRKKG"
      msa: /path/to/chainA.a3m
  - protein:
      id: [B]
      sequence: "AQVQLQESGGGLVQAGGSLRLSCAASERTFSTYAMGWFRQAPGREREFLAQINWSGTTTYYAESVKDRTTISRDNAKNTVYLEMNNLNADDTGIYFCAAHPQRGWGSTLGWTYWGQGTQVTVS"
      msa: /path/to/chainB.a3m
  - ligand:
      id: [C]
      ccd: PML
constraints:
  - bond:
      atom1: [A, 77, NZ]
      atom2: [C, 1, O72]
  - bond:
      atom1: [A, 8, NZ]
      atom2: [C, 1, O12]
```

If I recall correctly, I also tried no MSA and got the same error. Once again, your time is greatly appreciated. 

Best, 
G
