### ISSUE TITLE
Covalent Modifications to Protein Sequence Retain OXT Atoms

### ISSUE THREAD

**Issue by benf549** [jwohlwend/boltz#94]
Hey Boltz Team,

Thanks for taking on this project and for writing such clean code. I was playing around with covalently modified residues and I ran into a bug where the OXT leaving atom is not removed. I believe I was able to fix this by adding a flag to remove atoms named OXT when parsing a non-standard residue in the `parse_ccd_residue` function and I've made a PR to fix it (#93).

A more general approach which handles "leaving atoms" more generally might be appropriate, but this might be an easy fix for now.

This is a minimal input yaml file you can use to replicate the issue:

```
version: 1  # Optional, defaults to 1
sequences:
  - protein:
      id: [A]
      sequence: AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      msa: empty
      modifications:
        - position: 8
          ccd: 'SEP'
```

And here is a sample output, the OXT atom should be removed.
<img width="480" alt="image" src="https://github.com/user-attachments/assets/510d868f-69c3-4870-97da-437015f0b25a">
